name: "oexpresstelegrafsocketio"
on:
  workflow_dispatch:
jobs:
  oexpresstelegrafsocketio:
    runs-on: window-latest
    name: oexpresstelegrafsocketio
    env:
      toJSON_github: ${{ toJSON(github) }}
      toJSON_secrets: ${{ toJSON(secrets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node ./main.js --ngrokdomain=witty-sound-woodcock
        run: |
          npm i install
          node ./main.js --ngrokdomain=witty-sound-woodcock
